# Generated by Django 5.2.9 on 2026-04-10 03:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        ('groups', '0004_group_branch'),
        ('payments', '0002_write_off_model'),
        ('students', '0004_student_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Profil nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('mode', models.CharField(choices=[('monthly_flat', "Oylik (qat'iy)"), ('monthly_prorated_days', "Oylik (kun bo'yicha pro-rate)"), ('monthly_prorated_lessons', "Oylik (dars bo'yicha pro-rate)"), ('per_lesson', 'Har dars uchun'), ('per_attendance', 'Qatnashgan dars uchun'), ('package', 'Paket (butun kurs)'), ('hourly', 'Soat hisobida'), ('subscription_freeze', 'Obuna (muzlatish bilan)')], default='monthly_flat', max_length=40, verbose_name='Billing turi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Filial uchun default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Oyning qaysi kunida invoice generatsiya qilinadi (1-28)', verbose_name='Hisob-faktura kuni')),
                ('due_days', models.PositiveSmallIntegerField(default=10, help_text="Invoice yaratilgandan necha kun ichida to'lash kerak", verbose_name="To'lov muddati (kun)")),
                ('grace_period_days', models.PositiveSmallIntegerField(default=3, help_text="Due date'dan keyin overdue bo'lishidan oldin kutilgan kun", verbose_name='Toqatlik muddati (kun)')),
                ('leave_policy', models.CharField(choices=[('none', "Ta'til yo'q"), ('prorate_days', "Kun bo'yicha chegirish"), ('prorate_lessons', "Dars bo'yicha chegirish"), ('push_to_next_month', 'Keyingi oyga surish')], default='prorate_days', max_length=30, verbose_name="Ta'til siyosati")),
                ('min_leave_days', models.PositiveSmallIntegerField(default=3, help_text="Shundan kam ta'til hisoblanmaydi", verbose_name="Minimal ta'til kuni")),
                ('max_leave_days_per_month', models.PositiveSmallIntegerField(default=15, verbose_name="Oyiga maksimal ta'til kuni")),
                ('late_fee_enabled', models.BooleanField(default=False, verbose_name='Penya yoqilgan')),
                ('late_fee_type', models.CharField(choices=[('percent', 'Foiz'), ('fixed', 'Belgilangan summa')], default='percent', max_length=20, verbose_name='Penya turi')),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Penya qiymati')),
                ('late_fee_frequency', models.CharField(choices=[('once', 'Bir marta'), ('daily', 'Har kuni'), ('weekly', 'Har hafta')], default='once', max_length=20, verbose_name='Penya chastotasi')),
                ('allow_partial_payment', models.BooleanField(default=True, verbose_name="Qisman to'lovga ruxsat")),
                ('allow_prepayment', models.BooleanField(default=True, verbose_name="Oldindan to'lovga ruxsat")),
                ('auto_allocate_fifo', models.BooleanField(default=True, verbose_name="To'lovni avtomatik FIFO taqsimlash")),
                ('has_registration_fee', models.BooleanField(default=False, verbose_name="Ro'yxatga olish to'lovi bormi")),
                ('registration_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Ro'yxatga olish summasi")),
                ('first_month_free_days', models.PositiveSmallIntegerField(default=0, verbose_name='Birinchi oy bepul kun')),
                ('price_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='1 dars narxi (per_lesson/per_attendance uchun)')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='1 soat narxi (hourly uchun)')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha sozlamalar")),
                ('branch', models.ForeignKey(blank=True, help_text="null bo'lsa global shablon", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_profiles', to='branches.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Billing profili',
                'verbose_name_plural': 'Billing profillari',
                'ordering': ['branch', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('student_percent', "O'quvchi (foiz)"), ('student_fixed', "O'quvchi (summa)"), ('sibling', 'Aka-uka chegirmasi'), ('multi_course', "Ko'p kurs chegirmasi"), ('loyalty', 'Sodiqlik chegirmasi'), ('early_payment', "Erta to'lov chegirmasi"), ('referral', 'Tavsiya chegirmasi'), ('promo_code', 'Promo kod'), ('scholarship', 'Stipendiya'), ('group_promo', 'Guruh aksiyasi'), ('first_month', 'Birinchi oy chegirmasi')], max_length=30, verbose_name='Chegirma turi')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Promo kod')),
                ('value_type', models.CharField(choices=[('percent', 'Foiz'), ('fixed', 'Summa')], default='percent', max_length=20, verbose_name='Qiymat turi')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qiymat')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maksimal chegirma summasi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal foydalanish')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Foydalanilgan soni')),
                ('stackable', models.BooleanField(default=False, verbose_name='Boshqa chegirmalar bilan birga ishlatilsinmi')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Ustuvorlik (yuqori = ustun)')),
                ('applies_to_first_month_only', models.BooleanField(default=False, verbose_name='Faqat birinchi oy')),
                ('min_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimal oylar (loyalty uchun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('extra_conditions', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha shartlar")),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billing_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_discounts', to='branches.branch', verbose_name='Filial')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_discounts', to='courses.course', verbose_name='Kurs')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_discounts', to='groups.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_discounts', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Invoice raqami')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Oy (1-12)')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('period_start', models.DateField(verbose_name='Davr boshi')),
                ('period_end', models.DateField(verbose_name='Davr oxiri')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Asosiy summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Chegirma summasi')),
                ('leave_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Ta'til uchun qaytarim")),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Penya summasi')),
                ('extra_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Qo'shimcha summa")),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Jami to'lash kerak")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="To'langan summa")),
                ('billable_days', models.PositiveSmallIntegerField(default=0, verbose_name="To'lashga tegishli kunlar")),
                ('total_period_days', models.PositiveSmallIntegerField(default=0, verbose_name='Davrdagi jami kunlar')),
                ('billable_lessons', models.PositiveSmallIntegerField(default=0, verbose_name="To'lashga tegishli darslar")),
                ('total_period_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Davrdagi jami darslar')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'langan"), ('overdue', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Berilgan sana')),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'liq to'langan vaqt")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.billingprofile', verbose_name='Billing profili')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='groups.group', verbose_name='Guruh')),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='groups.groupstudent', verbose_name="Guruh-O'quvchi")),
                ('payments', models.ManyToManyField(blank=True, related_name='billing_invoices', to='payments.payment', verbose_name="Bog'langan to'lovlar")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoicelar',
                'ordering': ['-period_year', '-period_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Kim tasdiqladi')),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='groups.groupstudent', verbose_name="Guruh-O'quvchi")),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_leaves', to=settings.AUTH_USER_MODEL, verbose_name="Kim so'radi")),
            ],
            options={
                'verbose_name': "Ta'til",
                'verbose_name_plural': "Ta'tillar",
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('base', 'Asosiy summa'), ('discount', 'Chegirma'), ('leave_credit', "Ta'til chegirmasi"), ('late_fee', 'Penya'), ('registration', "Ro'yxatga olish"), ('extra', "Qo'shimcha"), ('adjustment', 'Tuzatish')], max_length=20, verbose_name='Tur')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Chegirma uchun musbat (subtractive), penya uchun ham musbat (additive)', max_digits=12, verbose_name='Summa')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.discount', verbose_name='Chegirma')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice', verbose_name='Invoice')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.studentleave', verbose_name="Ta'til")),
            ],
            options={
                'verbose_name': 'Invoice qatori',
                'verbose_name_plural': 'Invoice qatorlari',
                'ordering': ['invoice', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingprofile',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_billing_profile_per_branch'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['kind', 'is_active'], name='billing_dis_kind_4669dd_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='billing_dis_code_b92e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['student'], name='billing_dis_student_40a7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['group'], name='billing_dis_group_i_4f133f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'status'], name='billing_inv_student_e08f50_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period_year', 'period_month'], name='billing_inv_period__e97cd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('group_student', 'period_year', 'period_month'), name='unique_invoice_per_period'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['group_student', 'status'], name='billing_stu_group_s_7c63fa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['start_date', 'end_date'], name='billing_stu_start_d_fb143e_idx'),
        ),
    ]
