# Generated by Django 5.2.9 on 2026-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('groups', '0004_group_branch'),
        ('payments', '0002_write_off_model'),
        ('students', '0004_student_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_period',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('group_student', 'period_year', 'period_month'), name='unique_invoice_per_period'),
        ),
    ]
