# Generated by Django 5.2.9 on 2025-12-04 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#EF4444", max_length=7, verbose_name="Rang"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Xarajat kategoriyasi",
                "verbose_name_plural": "Xarajat kategoriyalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Xarajat sanasi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="paid",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Chek/Kvitansiya",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Takroriy"),
                ),
                (
                    "recurring_day",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Har oyning qaysi kuni"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim tasdiqladi",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim kiritdi",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.expensecategory",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xarajat",
                "verbose_name_plural": "Xarajatlar",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_month", models.PositiveIntegerField(verbose_name="Oy")),
                ("period_year", models.PositiveIntegerField(verbose_name="Yil")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Asosiy ish haqi",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Bonus"
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Ushlab qolish",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Jami"
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(default=0, verbose_name="Jami darslar"),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jami o'quvchilar"
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hisoblash tafsilotlari"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculated", "Hisoblangan"),
                            ("approved", "Tasdiqlangan"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="calculated",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tasdiqlangan vaqt"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'langan vaqt"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tasdiqlagan",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="To'lagan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries",
                        to="teachers.teacher",
                        verbose_name="O'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish haqi",
                "verbose_name_plural": "Ish haqlari",
                "ordering": ["-period_year", "-period_month"],
                "unique_together": {("teacher", "period_month", "period_year")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Kirim"),
                            ("expense", "Chiqim"),
                            ("transfer", "O'tkazma"),
                            ("refund", "Qaytarish"),
                            ("salary", "Ish haqi"),
                        ],
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Sana")),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim kiritdi",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.expense",
                        verbose_name="Xarajat",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.payment",
                        verbose_name="To'lov",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.salary",
                        verbose_name="Ish haqi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranzaksiya",
                "verbose_name_plural": "Tranzaksiyalar",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
