# Generated by Django 5.2.9 on 2025-12-04 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Qo'shimcha telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tug'ilgan sana"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Erkak"), ("female", "Ayol")],
                        max_length=10,
                        null=True,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Manzil"),
                ),
                (
                    "parent_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ota-ona ismi",
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Ota-ona telefoni",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("inactive", "Faol emas"),
                            ("graduated", "Bitirgan"),
                            ("dropped", "Chiqib ketgan"),
                            ("frozen", "Muzlatilgan"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "enrolled_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Balans",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram username",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Veb-sayt"),
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("referral", "Tavsiya"),
                            ("walk_in", "O'zi keldi"),
                            ("other", "Boshqa"),
                        ],
                        default="walk_in",
                        max_length=50,
                        verbose_name="Manba",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quvchi",
                "verbose_name_plural": "O'quvchilar",
                "ordering": ["-created_at"],
            },
        ),
    ]
