# Generated by Django 5.2.9 on 2026-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="archive_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Arxiv sababi"),
        ),
        migrations.AddField(
            model_name="student",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Arxivga olingan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="freeze_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Muzlatish oxiri"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="freeze_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Muzlatish sababi"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="freeze_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Muzlatish boshi"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="passport_series",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Pasport seriya raqami",
            ),
        ),
    ]
