# Generated by Django 5.2.9 on 2026-03-22 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("students", "0002_student_archive_reason_student_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nomi"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="HEX formatda: #FF5733",
                        max_length=7,
                        verbose_name="Rang",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tavsif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Teg",
                "verbose_name_plural": "Teglar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="Ob'ekt ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Model turi",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="students.tag",
                        verbose_name="Teg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teg bog'lanishi",
                "verbose_name_plural": "Teg bog'lanishlari",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="students_ta_content_e8739e_idx",
                    )
                ],
                "unique_together": {("tag", "content_type", "object_id")},
            },
        ),
    ]
