# Generated by Django 5.2.9 on 2026-03-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("students", "0003_tag_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="branches.branch",
                verbose_name="Filial",
            ),
        ),
    ]
