# Generated by Django 5.2.9 on 2026-04-22 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_billing_profile_groupstudent_billing_profile_and_more'),
        ('students', '0004_student_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('behavior', 'Xulq'), ('progress', "O'zlashtirish"), ('parent_contact', 'Ota-ona bilan aloqa'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Tepada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_group_notes', to=settings.AUTH_USER_MODEL, verbose_name='Kim yozdi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='groups.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notes', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Guruh izohi',
                'verbose_name_plural': 'Guruh izohlari',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
