# Generated by Django 5.2.9 on 2025-12-04 22:10

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice raqami"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Davr boshi")),
                ("period_end", models.DateField(verbose_name="Davr oxiri")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Jami summa"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Chegirma",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Umumiy summa"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UZS", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("pending", "Kutilmoqda"),
                            ("paid", "To'langan"),
                            ("overdue", "Muddati o'tgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="To'lov muddati")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'langan vaqt"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
            ],
            options={
                "verbose_name": "Billing Invoice",
                "verbose_name_plural": "Billing Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                        verbose_name="Tarif turi",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Oylik narx"
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Yillik narx"
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(default=50, verbose_name="Max o'quvchilar"),
                ),
                (
                    "max_groups",
                    models.IntegerField(default=10, verbose_name="Max guruhlar"),
                ),
                (
                    "max_teachers",
                    models.IntegerField(default=5, verbose_name="Max o'qituvchilar"),
                ),
                (
                    "max_admins",
                    models.IntegerField(default=2, verbose_name="Max adminlar"),
                ),
                (
                    "features",
                    models.JSONField(default=dict, verbose_name="Imkoniyatlar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Mashhur"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Tartib")),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tariflar",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="BillingPayment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UZS", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Karta"),
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("transfer", "Bank o'tkazmasi"),
                        ],
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("completed", "Bajarildi"),
                            ("failed", "Xato"),
                            ("refunded", "Qaytarildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tashqi ID"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shared.billinginvoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Payment",
                "verbose_name_plural": "Billing Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Markaz nomi")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Egasi ismi"),
                ),
                (
                    "owner_email",
                    models.EmailField(max_length=254, verbose_name="Egasi email"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=20, verbose_name="Egasi telefoni"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Manzil"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Shahar"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tenants/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Sinov"),
                            ("active", "Faol"),
                            ("suspended", "To'xtatilgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sinov tugash vaqti"
                    ),
                ),
                (
                    "subscription_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Obuna tugash vaqti"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sozlamalar"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Tashkent",
                        max_length=50,
                        verbose_name="Vaqt zonasi",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="uz", max_length=10, verbose_name="Til"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UZS", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="shared.plan",
                        verbose_name="Tarif rejasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Markaz",
                "verbose_name_plural": "Markazlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domainlar",
            },
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_invoices",
                to="shared.tenant",
                verbose_name="Markaz",
            ),
        ),
    ]
