# Generated by Django 5.2.9 on 2026-04-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_unique_invoice_per_period_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='billing_profile',
            field=models.ForeignKey(blank=True, help_text="Bo'sh qolsa filial default ishlatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='billing.billingprofile', verbose_name='Billing profili'),
        ),
    ]
