# Generated by Django 5.2.9 on 2025-12-04 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Familiya"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Qo'shimcha telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("contacted", "Bog'lanildi"),
                            ("interested", "Qiziqdi"),
                            ("trial", "Sinov darsida"),
                            ("negotiation", "Kelishilmoqda"),
                            ("converted", "O'quvchi bo'ldi"),
                            ("lost", "Yo'qotildi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Veb-sayt"),
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("facebook", "Facebook"),
                            ("referral", "Tavsiya"),
                            ("walk_in", "O'zi keldi"),
                            ("phone", "Telefon qo'ng'iroq"),
                            ("other", "Boshqa"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="Manba",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("medium", "O'rta"),
                            ("high", "Yuqori"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Muhimlik",
                    ),
                ),
                (
                    "next_contact_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Keyingi aloqa vaqti"
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Konversiya vaqti"
                    ),
                ),
                (
                    "lost_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Yo'qotish sababi"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mas'ul",
                    ),
                ),
                (
                    "converted_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_source",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
                (
                    "interested_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="courses.course",
                        verbose_name="Qiziqgan kurs",
                    ),
                ),
                (
                    "interested_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="courses.subject",
                        verbose_name="Qiziqgan fan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leadlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Qo'ng'iroq"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("meeting", "Uchrashuv"),
                            ("trial", "Sinov dars"),
                            ("note", "Izoh"),
                            ("status_change", "Status o'zgarishi"),
                        ],
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "call_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qo'ng'iroq davomiyligi (sekund)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim qildi",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead faoliyati",
                "verbose_name_plural": "Lead faoliyatlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
