# Generated by Django 5.2.9 on 2026-03-22 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ism")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "center_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="O'quv markaz nomi",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Xabar"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("contacted", "Bog'lanildi"),
                            ("demo_done", "Demo ko'rsatildi"),
                            ("converted", "Mijoz bo'ldi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Admin izohi"),
                ),
            ],
            options={
                "verbose_name": "Demo so'rov",
                "verbose_name_plural": "Demo so'rovlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
