# Generated by Django 5.2.9 on 2025-12-04 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("start_date", models.DateField(verbose_name="Boshlanish sanasi")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                (
                    "days",
                    models.JSONField(
                        default=list,
                        help_text="[0,2,4] = Dush, Chor, Juma",
                        verbose_name="Kunlar",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("end_time", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Xona"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Max o'quvchilar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Shakllanmoqda"),
                            ("active", "Faol"),
                            ("completed", "Tugallangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="forming",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bo'sh qolsa kurs narxi ishlatiladi",
                        max_digits=12,
                        null=True,
                        verbose_name="Narxi (oylik)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="teachers.teacher",
                        verbose_name="O'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guruh",
                "verbose_name_plural": "Guruhlar",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="GroupStudent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("completed", "Tugallagan"),
                            ("dropped", "Chiqib ketgan"),
                            ("transferred", "Ko'chirilgan"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana"),
                ),
                (
                    "left_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Chiqib ketgan sana"
                    ),
                ),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maxsus narx",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Chegirma %",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guruh o'quvchisi",
                "verbose_name_plural": "Guruh o'quvchilari",
                "ordering": ["student__first_name"],
                "unique_together": {("group", "student")},
            },
        ),
    ]
