# Generated by Django 5.2.9 on 2026-03-22 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="rooms.room",
                verbose_name="Xona",
            ),
        ),
    ]
