# Generated by Django 5.2.9 on 2026-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstudent",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Guruh balansi"
            ),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="exception_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Istisno oxiri"),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="exception_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Istisno sababi"
            ),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="exception_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Istisno boshi"),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="exception_sum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Istisno summa",
            ),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="last_write_off_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Oxirgi yechib olish sanasi"
            ),
        ),
        migrations.AddField(
            model_name="groupstudent",
            name="next_write_off_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Keyingi yechib olish sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="groupstudent",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("completed", "Tugallagan"),
                    ("dropped", "Chiqib ketgan"),
                    ("transferred", "Ko'chirilgan"),
                    ("frozen", "Muzlatilgan"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
