# Generated by Django 5.2.9 on 2026-04-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_unique_invoice_per_period_and_more'),
        ('groups', '0004_group_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='billing_profile',
            field=models.ForeignKey(blank=True, help_text="Bo'sh qolsa kurs yoki filial default ishlatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='billing.billingprofile', verbose_name='Billing profili'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='billing_profile',
            field=models.ForeignKey(blank=True, help_text="Bo'sh qolsa guruh yoki filial default ishlatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_students', to='billing.billingprofile', verbose_name='Billing profili (individual)'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='joined_date',
            field=models.DateField(help_text="O'quvchi guruhga qo'shilgan sana (billing hisob-kitob uchun muhim)", verbose_name="Qo'shilgan sana"),
        ),
    ]
