# Generated by Django 5.2.9 on 2025-12-04 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Foiz"), ("fixed", "Belgilangan summa")],
                        default="percent",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Qiymat"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Boshlanish")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Tugash"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Sabab"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chegirma",
                "verbose_name_plural": "Chegirmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("transfer", "O'tkazma"),
                            ("payme", "Payme"),
                            ("click", "Click"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("tuition", "O'qish to'lovi"),
                            ("registration", "Ro'yxatga olish"),
                            ("material", "Material"),
                            ("other", "Boshqa"),
                        ],
                        default="tuition",
                        max_length=20,
                        verbose_name="To'lov turi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("completed", "Qabul qilindi"),
                            ("cancelled", "Bekor qilindi"),
                            ("refunded", "Qaytarildi"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "period_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Oy (1-12)"
                    ),
                ),
                (
                    "period_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Yil"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Kvitansiya raqami"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tashqi ID (Payme/Click)",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim qabul qildi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice raqami"
                    ),
                ),
                ("period_month", models.PositiveIntegerField(verbose_name="Oy (1-12)")),
                ("period_year", models.PositiveIntegerField(verbose_name="Yil")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Chegirma",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Jami"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="To'langan summa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("sent", "Yuborilgan"),
                            ("paid", "To'langan"),
                            ("partial", "Qisman to'langan"),
                            ("overdue", "Muddati o'tgan"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="To'lov muddati")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'langan vaqt"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
                (
                    "payments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices_paid",
                        to="payments.payment",
                        verbose_name="To'lovlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoicelar",
                "ordering": ["-period_year", "-period_month"],
                "unique_together": {
                    ("student", "group", "period_month", "period_year")
                },
            },
        ),
    ]
