# Generated by Django 5.2.9 on 2026-03-22 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "groups",
            "0003_groupstudent_balance_groupstudent_exception_end_date_and_more",
        ),
        ("payments", "0001_initial"),
        ("students", "0002_student_archive_reason_student_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Yechib olingan summa",
                    ),
                ),
                ("period_month", models.PositiveIntegerField(verbose_name="Oy (1-12)")),
                ("period_year", models.PositiveIntegerField(verbose_name="Yil")),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Oldingi balans"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Keyingi balans"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_offs",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "group_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_offs",
                        to="groups.groupstudent",
                        verbose_name="Guruh-O'quvchi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_offs",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yechib olish",
                "verbose_name_plural": "Yechib olishlar",
                "ordering": ["-created_at"],
                "unique_together": {("group_student", "period_month", "period_year")},
            },
        ),
    ]
