# Generated by Django 5.2.9 on 2025-12-04 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Keldi"),
                            ("absent", "Kelmadi"),
                            ("late", "Kechikdi"),
                            ("excused", "Sababli"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim belgiladi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Davomat",
                "verbose_name_plural": "Davomatlar",
                "ordering": ["-date", "student__first_name"],
                "unique_together": {("group", "student", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jami o'quvchilar"
                    ),
                ),
                (
                    "present_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kelganlar"),
                ),
                (
                    "absent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kelmaganlar"),
                ),
                (
                    "late_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kechikkanlar"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim yaratdi",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Davomat sessiyasi",
                "verbose_name_plural": "Davomat sessiyalari",
                "ordering": ["-date"],
                "unique_together": {("group", "date")},
            },
        ),
    ]
