# Generated by Django 5.2.9 on 2026-03-22 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Bir necha kunlik bayramlar uchun",
                        null=True,
                        verbose_name="Tugash sanasi",
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "Davlat bayrami"),
                            ("religious", "Diniy bayram"),
                            ("custom", "Markaz dam olishi"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
            ],
            options={
                "verbose_name": "Dam olish kuni",
                "verbose_name_plural": "Dam olish kunlari",
                "ordering": ["date"],
            },
        ),
    ]
