# Generated by Django 5.2.9 on 2026-04-22 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_holiday_model'),
        ('groups', '0005_group_billing_profile_groupstudent_billing_profile_and_more'),
        ('students', '0004_student_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('score', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Baho (0-5)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_grades_given', to=settings.AUTH_USER_MODEL, verbose_name="Kim bahoni qo'ydi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='groups.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Dars bahosi',
                'verbose_name_plural': 'Dars baholari',
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('group', 'student', 'date')},
            },
        ),
    ]
