# Generated by Django 5.2.9 on 2025-12-04 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Qo'shimcha telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/photos/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tug'ilgan sana"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Manzil"),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Belgilangan"),
                            ("hourly", "Soatlik"),
                            ("percent", "Foizli"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Ish haqi turi",
                    ),
                ),
                (
                    "salary_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Ish haqi miqdori",
                    ),
                ),
                (
                    "salary_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Ish haqi foizi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("inactive", "Faol emas"),
                            ("on_leave", "Ta'tilda"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishga kirgan sana"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram username",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="courses.subject",
                        verbose_name="Fanlar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'qituvchi",
                "verbose_name_plural": "O'qituvchilar",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
