# Generated by Django 5.2.9 on 2026-03-22 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Yaratish"),
                            ("update", "Yangilash"),
                            ("delete", "O'chirish"),
                            ("login", "Kirish"),
                            ("logout", "Chiqish"),
                            ("password_change", "Parol o'zgartirish"),
                            ("payment", "To'lov"),
                            ("refund", "Qaytarish"),
                            ("transfer", "O'tkazish"),
                            ("export", "Eksport"),
                        ],
                        max_length=20,
                        verbose_name="Amal",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Model nomi"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ob'ekt ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Ob'ekt tavsifi",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"field": {"old": "...", "new": "..."}}',
                        verbose_name="O'zgarishlar",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP manzil"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit loglar",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_audit_user_id_429f6b_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_audit_model_n_20c0d3_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                ],
            },
        ),
    ]
