# Generated by Django 5.2.9 on 2026-03-22 05:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_alter_group_room"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz (tez test)"),
                            ("midterm", "Oraliq imtihon"),
                            ("final", "Yakuniy imtihon"),
                            ("placement", "Daraja aniqlash"),
                            ("mock", "Sinov imtihon"),
                        ],
                        default="quiz",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=6,
                        verbose_name="Maksimal ball",
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        max_digits=6,
                        verbose_name="O'tish bali",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="Imtihon sanasi")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Boshlanish vaqti"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Davomiyligi (daqiqa)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("scheduled", "Rejalashtirilgan"),
                            ("in_progress", "O'tkazilmoqda"),
                            ("completed", "Tugallangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim yaratdi",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon",
                "verbose_name_plural": "Imtihonlar",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=6,
                        verbose_name="Maksimal ball",
                    ),
                ),
                ("assigned_date", models.DateField(verbose_name="Berilgan sana")),
                ("due_date", models.DateField(verbose_name="Topshirish muddati")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("closed", "Yopilgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homeworks/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homeworks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim berdi",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uy vazifasi",
                "verbose_name_plural": "Uy vazifalari",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ball",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("graded", "Baholangan"),
                            ("absent", "Kelmagan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Baholangan vaqt"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                        verbose_name="Imtihon",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim baholadi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon natijasi",
                "verbose_name_plural": "Imtihon natijalari",
                "ordering": ["-score"],
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ball",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Topshirilmagan"),
                            ("submitted", "Topshirilgan"),
                            ("graded", "Baholangan"),
                            ("late", "Kechikib topshirilgan"),
                            ("resubmit", "Qayta topshirish kerak"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Topshirilgan vaqt"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework_submissions/",
                        verbose_name="Topshiriq fayli",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'quvchi izohi"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'qituvchi izohi"
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim baholadi",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.homework",
                        verbose_name="Vazifa",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submissions",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazifa topshirish",
                "verbose_name_plural": "Vazifa topshirishlar",
                "ordering": ["-submitted_at"],
                "unique_together": {("homework", "student")},
            },
        ),
    ]
