# Generated by Django 5.2.9 on 2026-03-22 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        ("groups", "0002_alter_group_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveIntegerField(verbose_name="Dars raqami"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Mavzu")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dars maqsadlari"
                    ),
                ),
                (
                    "materials",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Materiallar (darslik, video, link...)",
                    ),
                ),
                (
                    "homework_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Uy vazifasi tavsifi"
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Dars sanasi"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Davomiylik (daqiqa)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("ready", "Tayyor"),
                            ("completed", "O'tildi"),
                            ("cancelled", "Bekor"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'qituvchi eslatmalari"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars rejasi",
                "verbose_name_plural": "Dars rejalari",
                "ordering": ["group", "lesson_number"],
                "unique_together": {("group", "lesson_number")},
            },
        ),
    ]
