# Generated by Django 5.2.9 on 2025-12-04 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Sana")),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("active_students", models.PositiveIntegerField(default=0)),
                ("new_students", models.PositiveIntegerField(default=0)),
                ("total_groups", models.PositiveIntegerField(default=0)),
                ("active_groups", models.PositiveIntegerField(default=0)),
                ("total_teachers", models.PositiveIntegerField(default=0)),
                ("active_teachers", models.PositiveIntegerField(default=0)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_leads", models.PositiveIntegerField(default=0)),
                ("converted_leads", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kunlik statistika",
                "verbose_name_plural": "Kunlik statistikalar",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyStats",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Yil")),
                ("month", models.PositiveIntegerField(verbose_name="Oy")),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("new_students", models.PositiveIntegerField(default=0)),
                ("dropped_students", models.PositiveIntegerField(default=0)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_leads", models.PositiveIntegerField(default=0)),
                ("converted_leads", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Oylik statistika",
                "verbose_name_plural": "Oylik statistikalar",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
    ]
