# Generated by Django 5.2.9 on 2026-03-22 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("address", models.TextField(verbose_name="Manzil")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Qo'shimcha telefon",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Shahar"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tuman"
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="Yaqin atrofdagi taniqli joy",
                        max_length=255,
                        null=True,
                        verbose_name="Mo'ljal",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kenglik (lat)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Uzunlik (lng)",
                    ),
                ),
                (
                    "working_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"start": "08:00", "end": "21:00"}',
                        verbose_name="Ish vaqti",
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[0,1,2,3,4,5] = Dush-Shanba",
                        verbose_name="Ish kunlari",
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Boshqaruvchi ismi",
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Boshqaruvchi telefoni",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Faol"), ("inactive", "Faol emas")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Asosiy filial"),
                ),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiallar",
                "ordering": ["-is_main", "name"],
            },
        ),
    ]
