# Generated by Django 5.2.9 on 2026-03-22 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "number",
                    models.CharField(
                        help_text="Masalan: 101, A-201",
                        max_length=20,
                        unique=True,
                        verbose_name="Xona raqami",
                    ),
                ),
                ("floor", models.PositiveIntegerField(default=1, verbose_name="Qavat")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("classroom", "Sinf xona"),
                            ("lab", "Laboratoriya"),
                            ("conference", "Majlis xonasi"),
                            ("office", "Ofis"),
                        ],
                        default="classroom",
                        max_length=20,
                        verbose_name="Xona turi",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Sig'imi (o'rin)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("maintenance", "Ta'mirda"),
                            ("inactive", "Faol emas"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["proyektor", "doska", "kompyuter"]',
                        verbose_name="Jihozlar",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Proyektor"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=True, verbose_name="Doska"),
                ),
                (
                    "has_computers",
                    models.BooleanField(default=False, verbose_name="Kompyuterlar"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(default=False, verbose_name="Konditsioner"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="rooms/", verbose_name="Rasm"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Soatlik narx",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
            ],
            options={
                "verbose_name": "Xona",
                "verbose_name_plural": "Xonalar",
                "ordering": ["number"],
            },
        ),
    ]
