# Generated by Django 5.2.9 on 2025-12-04 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment", "To'lov"),
                            ("payment_reminder", "To'lov eslatmasi"),
                            ("attendance", "Davomat"),
                            ("group", "Guruh"),
                            ("schedule", "Jadval"),
                            ("system", "Tizim"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=255, verbose_name="Sarlavha shabloni"),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Masalan: Hurmatli {student_name}, sizning {month} oyi uchun to'lovingiz...",
                        verbose_name="Xabar shabloni",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="['telegram', 'sms', 'in_app']",
                        verbose_name="Kanallar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Xabarnoma shabloni",
                "verbose_name_plural": "Xabarnoma shablonlari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment", "To'lov"),
                            ("payment_reminder", "To'lov eslatmasi"),
                            ("attendance", "Davomat"),
                            ("group", "Guruh"),
                            ("schedule", "Jadval"),
                            ("system", "Tizim"),
                            ("marketing", "Marketing"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "Ilova ichida"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Kanal",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "Normal"),
                            ("high", "Yuqori"),
                            ("urgent", "Shoshilinch"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Muhimlik",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'qilgan vaqt"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Yuborilgan"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bog'langan model",
                    ),
                ),
                (
                    "related_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Bog'langan ID"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="teachers.teacher",
                        verbose_name="O'qituvchi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabarnoma",
                "verbose_name_plural": "Xabarnomalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "Ilova ichida"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Kanal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("sent", "Yuborildi"),
                            ("delivered", "Yetkazildi"),
                            ("failed", "Xato"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tashqi ID"
                    ),
                ),
                (
                    "response",
                    models.JSONField(blank=True, default=dict, verbose_name="Javob"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Xato xabari"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.notification",
                        verbose_name="Xabarnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabarnoma logi",
                "verbose_name_plural": "Xabarnoma loglari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["student", "is_read"], name="notificatio_student_e1d8e8_idx"
            ),
        ),
    ]
