# Generated by Django 5.2.9 on 2026-03-22 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoSMS",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("debt_reminder", "Qarz eslatmasi"),
                            ("payment_received", "To'lov qabul qilindi"),
                            ("birthday", "Tug'ilgan kun tabrigi"),
                            ("lesson_reminder", "Dars eslatmasi"),
                            ("group_joined", "Guruhga qo'shildi"),
                            ("group_left", "Guruhdan chiqdi"),
                            ("freeze_started", "Muzlatildi"),
                            ("write_off", "Oylik yechib olindi"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Trigger",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Masalan: Hurmatli {student_name}, sizning {amount} so'm qarzingiz bor.",
                        verbose_name="Xabar shabloni",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Avtomatik SMS",
                "verbose_name_plural": "Avtomatik SMSlar",
                "ordering": ["trigger"],
            },
        ),
    ]
