# Generated by Django 5.2.9 on 2026-03-22 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "groups",
            "0003_groupstudent_balance_groupstudent_exception_end_date_and_more",
        ),
        ("notifications", "0002_auto_sms_model"),
        ("students", "0002_student_archive_reason_student_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                ("remind_at", models.DateTimeField(verbose_name="Eslatish vaqti")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "Normal"),
                            ("high", "Yuqori"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Muhimlik",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Bajarildi"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bajarilgan vaqt"
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="Eslatildi"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim yaratdi",
                    ),
                ),
                (
                    "related_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="groups.group",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "related_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="students.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eslatma",
                "verbose_name_plural": "Eslatmalar",
                "ordering": ["remind_at"],
            },
        ),
    ]
